name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  


    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./devops-challenges/code/q16

    - name: Run Tests
      run: |
        python -m unittest tests/test_app.py
      working-directory: ./devops-challenges/code/q16

    - name: Build Docker Image
      run: |
        docker build -t broken-image .
      working-directory: ./devops-challenges/code/q16

    - name: Push to DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push broken-image
      working-directory: ./devops-challenges/code/q16
